### ISSUE TITLE
PyPI release

### ISSUE THREAD

**Issue by jayvdb** [matthiask/workbench#8]
Would it be possible to release this as an app on PyPI?
I would like to build an app which integrates workbench and [taigo](https://pypi.org/search/?q=taiga)

**Comment by matthiask** [comment]
Hmm, yes this would be possible (in principle); I'm running the app directly from a Git checkout so I fear a bit that the PyPI release will be outdated soon.

Integrating Workbench and Taiga sounds interesting. 

Are you using Workbench in production already? I am interested in success (and failure) stories. You'd probably have to change the hardcoded currency at least?

**Comment by jayvdb** [comment]
We havent tried workbench yet, but it looks good for our needs, except for the development part of the project management which is where Taiga would fit in (somehow .. :) ).  We are a Django shop, so we can easily adapt minor differences to our needs.

I was guessing the currency would be Euro; is that not correct?

**Comment by matthiask** [comment]
The currency is CHF (swiss francs) not EUR but differences in formatting will be small or even negligible. 

You can of course modify your local installation, but if you want to contribute back your changes that would be even better :-)

**Comment by jayvdb** [comment]
Regarding the PyPI package, I wouldnt mind if the PyPI release was a marked as pre-release, and not updated regularly.  The most important aspect is that the setup.py/pyproject.toml has a name that is reserved.  i.e. not workbench, because that is already taken : https://pypi.org/project/workbench/ = https://github.com/SuperCowPowers/workbench .

The next aspect is getting the project installation packaging to include the parts of the repo which are an "installable app".  This would ideally require some slight restructures to the repo, so that assets are placed inside the installable app directories, however setup.py can do some funky things to allow the assets to remain as-is, but then be transplanted inside the installable app directories when the sdist/wheels are built.

**Comment by matthiask** [comment]
https://pypi.org/project/workbench-crm/ There you go :-)

**Comment by jayvdb** [comment]
Thank you.
